### ISSUE TITLE
Ingesting some PDFs throws EOFError

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#101]
Ingesting certain PDFs using the `gwss:ingest_etd` rake task results in an EOFError that contains:
```rake aborted!
EOFError: end of file reached

Tasks: TOP => gwss:ingest_etd
(See full trace by running task with --trace)
Traceback (most recent call last):
  File "etd_loader.py", line 756, in <module>
    l.import_etds()
  File "etd_loader.py", line 491, in import_etds
    self.store.get(etd_id), self.ingest_depositor)
  File "etd_loader.py", line 615, in repo_import
    output = subprocess.check_output(command, cwd=self.ingest_path)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
```
Loading the PDFs via the front-end web UI is also unsuccessful.

**Comment by kerchner** [comment]
Note that Hyrax 1.1 adds a configuration option to turn off full-text extraction.  This would more easily allow us to turn off the extraction, then load items where extraction failed, then re-enable full-text extraction.  See https://github.com/samvera/hyrax/commit/b0a22b2de3886d37e1ee97b837325c9cdc760a85 which is part of https://github.com/samvera/hyrax/releases/tag/v1.1.0

**Comment by kerchner** [comment]
We are many Hyrax releases ahead now, and haven't seen this error in a long time.  We do have issues with very large attachments, but those may be ameliorated by allocating more memory and/or solr containers.  Closing this, can be reopened if ever needed.
