### ISSUE TITLE
Reset password link not working

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#170]
Currently results in an error page

<img width="538" alt="image" src="https://user-images.githubusercontent.com/3451175/44380160-b9630b80-a4d7-11e8-9e60-793ff92286ec.png">

and the following in the log:

```
I, [2018-08-21T00:18:11.272627 #29605]  INFO -- : [165ac932-fdb1-41e1-a2fa-912a0007542f] Started POST "/users/password?locale=en" for 128.164.101.99 at 2018-08-21 00:18:11 -0400
I, [2018-08-21T00:18:11.274092 #29605]  INFO -- : [165ac932-fdb1-41e1-a2fa-912a0007542f] Processing by Devise::PasswordsController#create as HTML
I, [2018-08-21T00:18:11.274163 #29605]  INFO -- : [165ac932-fdb1-41e1-a2fa-912a0007542f]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"Z7ZMcGjppnNnnqkcLhqq5pjasoVKGoC4X/FEfG4HXamJQ9FjlLiedg24QEd++i3xGUtFPF1o1Is8CnKMZAt0EA==", "user"=>{"email"=>"dan.kerchner@gmail.com"}, "commit"=>"Send me reset password instructions", "locale"=>"en"}
D, [2018-08-21T00:18:11.276982 #29605] DEBUG -- : [165ac932-fdb1-41e1-a2fa-912a0007542f]   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "dan.kerchner@gmail.com"], ["LIMIT", 1]]
D, [2018-08-21T00:18:11.278137 #29605] DEBUG -- : [165ac932-fdb1-41e1-a2fa-912a0007542f]   User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["reset_password_token", "795f44422d5b2d23b7842b97df1723c44b4dac4b921b08dceabca89e534a9dbb"], ["LIMIT", 1]]
D, [2018-08-21T00:18:11.278752 #29605] DEBUG -- : [165ac932-fdb1-41e1-a2fa-912a0007542f]    (0.1ms)  BEGIN
D, [2018-08-21T00:18:11.280509 #29605] DEBUG -- : [165ac932-fdb1-41e1-a2fa-912a0007542f]   SQL (0.3ms)  UPDATE "users" SET "reset_password_token" = $1, "reset_password_sent_at" = $2, "updated_at" = $3 WHERE "users"."id" = $4  [["reset_password_token", "795f44422d5b2d23b7842b97df1723c44b4dac4b921b08dceabca89e534a9dbb"], ["reset_password_sent_at", "2018-08-21 04:18:11.278471"], ["updated_at", "2018-08-21 04:18:11.279327"], ["id", 6]]
D, [2018-08-21T00:18:11.282462 #29605] DEBUG -- : [165ac932-fdb1-41e1-a2fa-912a0007542f]    (0.9ms)  COMMIT
I, [2018-08-21T00:18:11.283868 #29605]  INFO -- : [165ac932-fdb1-41e1-a2fa-912a0007542f]   Rendering /usr/local/rvm/gems/ruby-2.3.3/gems/devise-4.4.3/app/views/devise/mailer/reset_password_instructions.html.erb
I, [2018-08-21T00:18:11.285016 #29605]  INFO -- : [165ac932-fdb1-41e1-a2fa-912a0007542f]   Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/devise-4.4.3/app/views/devise/mailer/reset_password_instructions.html.erb (1.1ms)
D, [2018-08-21T00:18:11.285143 #29605] DEBUG -- : [165ac932-fdb1-41e1-a2fa-912a0007542f] Devise::Mailer#reset_password_instructions: processed outbound mail in 2.2ms
I, [2018-08-21T00:18:11.285344 #29605]  INFO -- : [165ac932-fdb1-41e1-a2fa-912a0007542f] Completed 500 Internal Server Error in 11ms (ActiveRecord: 2.2ms)
F, [2018-08-21T00:18:11.286995 #29605] FATAL -- : [165ac932-fdb1-41e1-a2fa-912a0007542f]   
F, [2018-08-21T00:18:11.287041 #29605] FATAL -- : [165ac932-fdb1-41e1-a2fa-912a0007542f] ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
F, [2018-08-21T00:18:11.287191 #29605] FATAL -- : [165ac932-fdb1-41e1-a2fa-912a0007542f]     2: 
[165ac932-fdb1-41e1-a2fa-912a0007542f]     3: <p>Someone has requested a link to change your password. You can do this through the link below.</p>
[165ac932-fdb1-41e1-a2fa-912a0007542f]     4: 
[165ac932-fdb1-41e1-a2fa-912a0007542f]     5: <p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p>
[165ac932-fdb1-41e1-a2fa-912a0007542f]     6: 
[165ac932-fdb1-41e1-a2fa-912a0007542f]     7: <p>If you didn't request this, please ignore this email.</p>
[165ac932-fdb1-41e1-a2fa-912a0007542f]     8: <p>Your password won't change until you access the link above and create a new one.</p>
F, [2018-08-21T00:18:11.287228 #29605] FATAL -- : [165ac932-fdb1-41e1-a2fa-912a0007542f]   
F, [2018-08-21T00:18:11.287276 #29605] FATAL -- : [165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/http/url.rb:62:in `full_url_for'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/http/url.rb:52:in `url_for'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:305:in `block in <class:RouteSet>'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:721:in `url_for'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:236:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:177:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:297:in `block (2 levels) in define_url_helper'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/routing/routes_proxy.rb:32:in `edit_user_password_url'
[165ac932-fdb1-41e1-a2fa-912a0007542f] devise (4.4.3) lib/devise/controllers/url_helpers.rb:53:in `block (4 levels) in generate_helpers!'
[165ac932-fdb1-41e1-a2fa-912a0007542f] devise (4.4.3) app/views/devise/mailer/reset_password_instructions.html.erb:5:in `__usr_local_rvm_gems_ruby_______gems_devise_______app_views_devise_mailer_reset_password_instructions_html_erb__4405103073492862182_69850482425500'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/template.rb:159:in `block in render'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/notifications.rb:166:in `instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/template.rb:354:in `instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/template.rb:157:in `render'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/notifications.rb:164:in `block in instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/notifications.rb:164:in `instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/renderer/template_renderer.rb:14:in `render'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/renderer/renderer.rb:42:in `render_template'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/renderer/renderer.rb:23:in `render'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/rendering.rb:104:in `_render_template'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/rendering.rb:83:in `render_to_body'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/abstract_controller/rendering.rb:26:in `render'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/base.rb:919:in `block in collect_responses_from_templates'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/base.rb:916:in `each'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/base.rb:916:in `each'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/base.rb:916:in `map'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/base.rb:916:in `collect_responses_from_templates'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/base.rb:908:in `collect_responses'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/base.rb:816:in `mail'
[165ac932-fdb1-41e1-a2fa-912a0007542f] devise (4.4.3) lib/devise/mailers/helpers.rb:19:in `devise_mail'
[165ac932-fdb1-41e1-a2fa-912a0007542f] devise (4.4.3) app/mailers/devise/mailer.rb:14:in `reset_password_instructions'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/abstract_controller/base.rb:188:in `process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:90:in `run_callbacks'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/abstract_controller/callbacks.rb:19:in `process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/abstract_controller/base.rb:126:in `process'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/rescuable.rb:23:in `block in process'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/rescuable.rb:22:in `process'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/rendering.rb:30:in `process'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/base.rb:595:in `block in process'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/notifications.rb:164:in `block in instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/notifications.rb:164:in `instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/base.rb:594:in `process'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/message_delivery.rb:105:in `block in processed_mailer'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/message_delivery.rb:104:in `tap'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/message_delivery.rb:104:in `processed_mailer'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionmailer (5.0.7) lib/action_mailer/message_delivery.rb:95:in `deliver_now'
[165ac932-fdb1-41e1-a2fa-912a0007542f] devise (4.4.3) lib/devise/models/authenticatable.rb:193:in `send_devise_notification'
[165ac932-fdb1-41e1-a2fa-912a0007542f] devise (4.4.3) lib/devise/models/recoverable.rb:99:in `send_reset_password_instructions_notification'
[165ac932-fdb1-41e1-a2fa-912a0007542f] devise (4.4.3) lib/devise/models/recoverable.rb:52:in `send_reset_password_instructions'
[165ac932-fdb1-41e1-a2fa-912a0007542f] devise (4.4.3) lib/devise/models/recoverable.rb:136:in `send_reset_password_instructions'
[165ac932-fdb1-41e1-a2fa-912a0007542f] devise (4.4.3) app/controllers/devise/passwords_controller.rb:15:in `create'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/abstract_controller/base.rb:188:in `process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_controller/metal/rendering.rb:30:in `process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:126:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:455:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:90:in `run_callbacks'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/abstract_controller/callbacks.rb:19:in `process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_controller/metal/rescue.rb:20:in `process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/notifications.rb:164:in `block in instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/notifications.rb:164:in `instrument'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activerecord (5.0.7) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/abstract_controller/base.rb:126:in `process'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionview (5.0.7) lib/action_view/rendering.rb:30:in `process'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_controller/metal.rb:190:in `dispatch'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_controller/metal.rb:262:in `dispatch'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/journey/router.rb:39:in `block in serve'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/journey/router.rb:26:in `each'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/journey/router.rb:26:in `serve'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:727:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] warden (1.2.7) lib/warden/manager.rb:35:in `catch'
[165ac932-fdb1-41e1-a2fa-912a0007542f] warden (1.2.7) lib/warden/manager.rb:35:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] rack (2.0.5) lib/rack/etag.rb:25:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] rack (2.0.5) lib/rack/head.rb:12:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
[165ac932-fdb1-41e1-a2fa-912a0007542f] rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] active-fedora (11.5.2) lib/active_fedora/ldp_cache.rb:26:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] flipflop (2.4.0) lib/flipflop/feature_cache.rb:12:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/callbacks.rb:90:in `run_callbacks'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] railties (5.0.7) lib/rails/rack/logger.rb:36:in `call_app'
[165ac932-fdb1-41e1-a2fa-912a0007542f] railties (5.0.7) lib/rails/rack/logger.rb:24:in `block in call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/tagged_logging.rb:26:in `tagged'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/tagged_logging.rb:69:in `tagged'
[165ac932-fdb1-41e1-a2fa-912a0007542f] railties (5.0.7) lib/rails/rack/logger.rb:24:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/middleware/request_id.rb:24:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] rack (2.0.5) lib/rack/method_override.rb:22:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] rack (2.0.5) lib/rack/runtime.rb:22:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] activesupport (5.0.7) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] actionpack (5.0.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] railties (5.0.7) lib/rails/engine.rb:522:in `call'
[165ac932-fdb1-41e1-a2fa-912a0007542f] passenger (5.1.7) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
[165ac932-fdb1-41e1-a2fa-912a0007542f] passenger (5.1.7) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
[165ac932-fdb1-41e1-a2fa-912a0007542f] passenger (5.1.7) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
[165ac932-fdb1-41e1-a2fa-912a0007542f] passenger (5.1.7) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
[165ac932-fdb1-41e1-a2fa-912a0007542f] passenger (5.1.7) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

May want to focus on:
```ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):```

**Comment by kerchner** [comment]
At least in a production deployment, this won't be needed after #11 is implemented.  However, it would still be broken for a deployment where Shibboleth is not configured (such as a dev environment) - but maybe not so critical in that case.   See out of this works in the Reference Implementation.

**Comment by kerchner** [comment]
The fix in https://github.com/gwu-libraries/isisfiles-hyrax/pull/96 fixes the same issue (https://github.com/gwu-libraries/isisfiles-hyrax/issues/72) in that repository.  Try applying the fix here.
