### ISSUE TITLE
Reindexing everything often fails

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#173]
The reindex_everything rake task often results in a timeout error:

```
rake aborted!
Faraday::TimeoutError: Net::ReadTimeout
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-encoding-0.0.4/lib/faraday/encoding.rb:12:in `call'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:35:in `block in get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/notifications.rb:166:in `instrument'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:33:in `get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/caching_connection.rb:13:in `get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/initializing_connection.rb:27:in `get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.2/lib/ldp/resource.rb:54:in `get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.2/lib/ldp/resource/rdf_source.rb:59:in `response_graph'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.2/lib/ldp/resource/rdf_source.rb:34:in `graph'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing/descendant_fetcher.rb:72:in `rdf_graph'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing/descendant_fetcher.rb:52:in `descendant_and_self_uris_partitioned'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing/descendant_fetcher.rb:38:in `descendant_and_self_uris'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing.rb:123:in `descendant_uris'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing.rb:92:in `reindex_everything'
/opt/scholarspace/scholarspace-hyrax/lib/tasks/gwss.rake:256:in `block (2 levels) in <top (required)>'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Net::ReadTimeout: Net::ReadTimeout
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-encoding-0.0.4/lib/faraday/encoding.rb:12:in `call'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:35:in `block in get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/notifications.rb:166:in `instrument'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:33:in `get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/caching_connection.rb:13:in `get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/initializing_connection.rb:27:in `get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.2/lib/ldp/resource.rb:54:in `get'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.2/lib/ldp/resource/rdf_source.rb:59:in `response_graph'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.2/lib/ldp/resource/rdf_source.rb:34:in `graph'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing/descendant_fetcher.rb:72:in `rdf_graph'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing/descendant_fetcher.rb:52:in `descendant_and_self_uris_partitioned'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing/descendant_fetcher.rb:38:in `descendant_and_self_uris'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing.rb:123:in `descendant_uris'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing.rb:92:in `reindex_everything'
/opt/scholarspace/scholarspace-hyrax/lib/tasks/gwss.rake:256:in `block (2 levels) in <top (required)>'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => gwss:reindex_everything
(See full trace by running task with --trace)
```

Reference this thread:  https://groups.google.com/forum/#!topic/samvera-tech/FPSFJubcPn8 and note solution offered by @cjcolvar

**Comment by kerchner** [comment]
Also see thread at https://jira.duraspace.org/browse/FCREPO-2544
