### ISSUE TITLE
Ingest rake task: Better handling of file names with special characters

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#233]
While technically speaking, `Figure 4 - Illustration of Holistic, Four-Dimensional Virtual Engineering Project Team (VEPT) Model.png` may be a valid file name, it causes problems in the `ingest_etd` rake task (and I would assume also in `ingest_work`.  Surrounding by quotes alone didn't effectively deal with the parentheses.

Error is:
```
Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/tmp3apr2fbj/Lumseyfai_gwu_0075A_55/Figure 4 - Illustration of Holistic
/opt/scholarspace/scholarspace-hyrax/lib/tasks/gwss.rake:247:in `initialize'
/opt/scholarspace/scholarspace-hyrax/lib/tasks/gwss.rake:247:in `open'
/opt/scholarspace/scholarspace-hyrax/lib/tasks/gwss.rake:247:in `block in attach_files'
/opt/scholarspace/scholarspace-hyrax/lib/tasks/gwss.rake:240:in `each'
/opt/scholarspace/scholarspace-hyrax/lib/tasks/gwss.rake:240:in `attach_files'
/opt/scholarspace/scholarspace-hyrax/lib/tasks/gwss.rake:136:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.5.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => gwss:ingest_etd
(See full trace by running task with --trace)
Traceback (most recent call last):
  File "etd_loader.py", line 764, in <module>
    l.import_etds()
  File "etd_loader.py", line 492, in import_etds
    self.store.get(etd_id), self.ingest_depositor)
  File "etd_loader.py", line 620, in repo_import
    output = subprocess.check_output(command, cwd=self.ingest_path)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rake', 'RAILS_ENV=production', 'gwss:ingest_etd', '--', '--manifest=/tmp/tmp3apr2fbj/metadata.json', '--primaryfile=/tmp/tmp3apr2fbj/Lumseyfai_gwu_0075A_14852.pdf', '--depositor=openaccess@gwu.edu', '--otherfiles=/tmp/tmp3apr2fbj/Lumseyfai_gwu_0075A_55/Figure 4 - Illustration of Holistic, Four-Dimensional Virtual Engineering Project Team (VEPT) Model.png']' returned non-zero exit status 1
```

This might be something to handle upstream in https://github.com/gwu-libraries/etd-loader and/or https://github.com/gwu-libraries/batch-loader and/or in the rake task.

For the moment, the particular ETD was loaded by manually fixing the file name in the tmp directory to remove special characters, and manually running the rake task with the updated file name.   File name Description metadata can be updated via the GWSS UI, but I am choosing not to at this time, to avert potential problems for future users who might download this file.

**Comment by kerchner** [comment]
Closing this issue; we have not encountered this issue with Bulkrax ETD loading.
