### ISSUE TITLE
Batch edit of works throws an error

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#316]
Attempting to batch-edit multiple works
![image](https://user-images.githubusercontent.com/3451175/153030441-683c05df-130e-48c4-b5ce-bca60e85e517.png)
throws an error:

```
D, [2022-02-08T11:22:49.409966 #6778] DEBUG -- : [f547c42a-18ec-4fc3-b3b6-db05d84d34fc]   Load LDP (9.4ms) http://gwfedora-test2.wrlc.org:8080/fcrepo/rest/prod/gq/67/js/06/gq67js06p Service: 507340
I, [2022-02-08T11:22:49.428226 #6778]  INFO -- : [f547c42a-18ec-4fc3-b3b6-db05d84d34fc] Completed 500 Internal Server Error in 46ms (ActiveRecord: 1.4ms)
F, [2022-02-08T11:22:49.428781 #6778] FATAL -- : [f547c42a-18ec-4fc3-b3b6-db05d84d34fc]   
F, [2022-02-08T11:22:49.428819 #6778] FATAL -- : [f547c42a-18ec-4fc3-b3b6-db05d84d34fc] ArgumentError (Unknown attribute volume):
F, [2022-02-08T11:22:49.428888 #6778] FATAL -- : [f547c42a-18ec-4fc3-b3b6-db05d84d34fc]   
F, [2022-02-08T11:22:49.428953 #6778] FATAL -- : [f547c42a-18ec-4fc3-b3b6-db05d84d34fc] app/forms/batch_edit_form.rb:49:in `block (2 levels) in initialize_combined_fields'
[f547c42a-18ec-4fc3-b3b6-db05d84d34fc] app/forms/batch_edit_form.rb:47:in `each'
[f547c42a-18ec-4fc3-b3b6-db05d84d34fc] app/forms/batch_edit_form.rb:47:in `block in initialize_combined_fields'
[f547c42a-18ec-4fc3-b3b6-db05d84d34fc] app/forms/batch_edit_form.rb:45:in `each'
[f547c42a-18ec-4fc3-b3b6-db05d84d34fc] app/forms/batch_edit_form.rb:45:in `each_with_object'
[f547c42a-18ec-4fc3-b3b6-db05d84d34fc] app/forms/batch_edit_form.rb:45:in `initialize_combined_fields'
[f547c42a-18ec-4fc3-b3b6-db05d84d34fc] app/forms/batch_edit_form.rb:21:in `initialize'
```

Note that `batch_edit_form.rb` contains fields/attributes that are not present on all Work types; this could be the source of the problem.

**Comment by dolsysmith** [comment]
Wondering how we want to handle a situation where someone might select works of different types to edit at once. The code as written creates a union of the fields available in the works in the batch. We could exclude fields that are not present in all the works (the simpler route), or we could try to prevent users from editing batches with different types of works.
