### ISSUE TITLE
PDF which fails MiniMagick characterization

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#64]
This file attachment fails to characterize and therefore fails to attach to the work.   Same result whether ingested via`ingest_etd` taks or whether via the web UI.   File can be found in https://drive.google.com/drive/folders/1sZRHFiilWkE4Gi_QGPSf7Qwge3yNxmd8?usp=sharing

From `production.log`:
```Completed 500 Internal Server Error in 8502ms (ActiveRecord: 8.9ms)
F, [2017-12-07T21:27:42.420887 #24419] FATAL -- : [2996f14e-2932-4c8a-8f72-891916867975]   
F, [2017-12-07T21:27:42.420938 #24419] FATAL -- : [2996f14e-2932-4c8a-8f72-891916867975] MiniMagick::Invalid (`identify /tmp/mini_magick20171207-24419-11kakyw.pdf` failed with error:
GPL Ghostscript 9.18: Unrecoverable error, exit code 1
):
F, [2017-12-07T21:27:42.420977 #24419] FATAL -- : [2996f14e-2932-4c8a-8f72-891916867975]   
F, [2017-12-07T21:27:42.421008 #24419] FATAL -- : [2996f14e-2932-4c8a-8f72-891916867975] app/services/hyrax/file_set_derivatives_service.rb:50:in `create_pdf_derivatives'
[2996f14e-2932-4c8a-8f72-891916867975] app/services/hyrax/file_set_derivatives_service.rb:24:in `create_derivatives'
```

This warrants some exploration outside of the scholarspace context, i.e. just with MiniMagick.

**Comment by kerchner** [comment]
Closing this issue as we have not seen these issues yet with newer versions of libraries, and with Bulkrax imports.  When #572 is merged and deployed, the new tasks will detect and catch up on any ProQuest ETDs that we had not loaded in the past due to issues like these.  If issues arise with any PDFs at that point, we will open new ticket(s).
