### ISSUE TITLE
ingest_etd breaks when metadata contains control characters

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#96]
We received an ETD whose metadata included `\t` characters in the description.  The `ingest_etd` task was unable to save the object.   Removing the `\t` characters resulted in a successful save.

```rake RAILS_ENV=production gwss:ingest_etd -- --manifest=/tmp/tmpdldxy1bd/metadata.json --primaryfile=/tmp/tmpdldxy1bd/Walker_gwu_0075A_10395.pdf --depositor=openaccess@gwu.edu
rake aborted!
Ldp::BadRequest: RDF was not parsable: [line: 8, col: 1 ] Broken token (newline): ;
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.0/lib/ldp/client/methods.rb:119:in `block in check_for_errors'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.0/lib/ldp/client/methods.rb:117:in `tap'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.0/lib/ldp/client/methods.rb:117:in `check_for_errors'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.0/lib/ldp/client/methods.rb:96:in `block in put'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:166:in `instrument'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.0/lib/ldp/client/methods.rb:88:in `put'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/caching_connection.rb:24:in `put'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/initializing_connection.rb:42:in `put'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.0/lib/ldp/resource.rb:84:in `create'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/ldp-0.7.0/lib/ldp/resource/rdf_source.rb:20:in `create'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/persistence.rb:180:in `_create_record'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing.rb:64:in `_create_record'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/callbacks.rb:240:in `block in _create_record'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:126:in `call'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/callbacks.rb:240:in `_create_record'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/persistence.rb:172:in `create_or_update'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/callbacks.rb:236:in `block in create_or_update'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:126:in `call'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/callbacks.rb:236:in `create_or_update'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/persistence.rb:33:in `save'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/validations.rb:50:in `save'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/associations/builder/orders.rb:44:in `save'
/opt/scholarspace/scholarspace-hyrax/lib/tasks/gwss.rake:93:in `ingest'
/opt/scholarspace/scholarspace-hyrax/lib/tasks/gwss.rake:54:in `block (2 levels) in <top (required)>'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => gwss:ingest_etd
(See full trace by running task with --trace)```

**Comment by kerchner** [comment]
Testing reveals that `\n` results in the same error.

**Comment by kerchner** [comment]
Note that even if a newline is inserted manually by editing the abstract/description field in the UI, the newline is not rendered when viewing the item page.

**Comment by kerchner** [comment]
This no longer seems to be a problem with the new Bulkrax-based ETD loading process (#555)
